//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RebateManagerEntities : DbContext
    {
        public RebateManagerEntities()
            : base("name=RebateManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comerciale> Comerciales { get; set; }
        public virtual DbSet<EstadosAprobacione> EstadosAprobaciones { get; set; }
        public virtual DbSet<EstadosSolicitudRebate> EstadosSolicitudRebates { get; set; }
        public virtual DbSet<FacturaDetalle> FacturaDetalles { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Obra> Obras { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Rebate> Rebates { get; set; }
        public virtual DbSet<Sectore> Sectores { get; set; }
        public virtual DbSet<SolicitudAprobacione> SolicitudAprobaciones { get; set; }
        public virtual DbSet<SolicitudesRebate> SolicitudesRebates { get; set; }
        public virtual DbSet<TipoComerciale> TipoComerciales { get; set; }
        public virtual DbSet<TipoFactura> TipoFacturas { get; set; }
        public virtual DbSet<TipoRebate> TipoRebates { get; set; }
        public virtual DbSet<TipoTransaccion> TipoTransaccions { get; set; }
        public virtual DbSet<TransaccionAprobacione> TransaccionAprobaciones { get; set; }
        public virtual DbSet<Transaccione> Transacciones { get; set; }
        public virtual DbSet<UnidadesNegocio> UnidadesNegocios { get; set; }
        public virtual DbSet<Zona> Zonas { get; set; }
    }
}
