//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudesRebate
    {
        public int SolicitudRebateId { get; set; }
        public string Codigo { get; set; }
        public int TipoRebateId { get; set; }
        public int ComercialId { get; set; }
        public decimal VolumenObjetivo { get; set; }
        public System.DateTime FechaTermino { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public string Periodo { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public System.DateTime FechaAprobacion { get; set; }
        public int EstadoSolicitudRebateId { get; set; }
    
        public virtual EstadosSolicitudRebate EstadosSolicitudRebate { get; set; }
        public virtual TipoRebate TipoRebate { get; set; }
    }
}
