//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Transacciones = new HashSet<Transaccione>();
        }
    
        public string CodigoFactura { get; set; }
        public int TipoFactura { get; set; }
        public string CodigoObra { get; set; }
        public string ComercialId { get; set; }
        public int ClienteId { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public decimal MontoTotal { get; set; }
        public decimal MontoImpuesto { get; set; }
        public decimal NontoSubTotal { get; set; }
    
        public virtual Comerciale Comerciale { get; set; }
        public virtual FacturaDetalle FacturaDetalle { get; set; }
        public virtual Obra Obra { get; set; }
        public virtual TipoFactura TipoFactura1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccione> Transacciones { get; set; }
    }
}
