//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public string CodigoFactura { get; set; }
        public int codigoDetalleFactura { get; set; }
        public Nullable<decimal> CantidadVenta { get; set; }
        public string Unidad { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string CodigoProducto { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
