//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rebate
    {
        public int RebateId { get; set; }
        public string Comentario { get; set; }
        public string Codigo { get; set; }
        public int TipoRebateId { get; set; }
        public decimal CantidadObjetivo { get; set; }
        public string PeriodoObjetivo { get; set; }
        public string ComercialEncargadoId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public int EstadoRebateId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Comerciale Comerciale { get; set; }
        public virtual TipoRebate TipoRebate { get; set; }
    }
}
