//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudAprobacione
    {
        public int SolicitudAprobacionId { get; set; }
        public Nullable<int> Orden { get; set; }
        public string ComercialAprobanteId { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> EstadoAprobacionId { get; set; }
        public Nullable<System.DateTime> FechaRepuesta { get; set; }
    
        public virtual Comerciale Comerciale { get; set; }
        public virtual TransaccionAprobacione TransaccionAprobacione { get; set; }
    }
}
