//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransaccionAprobacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransaccionAprobacione()
        {
            this.SolicitudAprobaciones = new HashSet<SolicitudAprobacione>();
        }
    
        public int TransaccionAprobacionId { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> TransaccionId { get; set; }
        public string ComercialAprobanteId { get; set; }
        public Nullable<int> EstadoAprobacionId { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
    
        public virtual Comerciale Comerciale { get; set; }
        public virtual EstadosAprobacione EstadosAprobacione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudAprobacione> SolicitudAprobaciones { get; set; }
        public virtual Transaccione Transaccione { get; set; }
    }
}
