//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaccione()
        {
            this.TransaccionAprobaciones = new HashSet<TransaccionAprobacione>();
        }
    
        public int TransaccionId { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> TipoTransaccionId { get; set; }
        public Nullable<int> TipoFacturacion { get; set; }
        public string CodigoFactura { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaAplicacion { get; set; }
        public Nullable<decimal> MontoAplicado { get; set; }
        public string ComercialId { get; set; }
    
        public virtual Comerciale Comerciale { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual TipoFactura TipoFactura { get; set; }
        public virtual TipoTransaccion TipoTransaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransaccionAprobacione> TransaccionAprobaciones { get; set; }
    }
}
